### ISSUE TITLE
Implement LoadLocation function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#157] opened 2018-10-19 22:38 UTC
From the SPEC:

LoadLoacation loads a locations from a time zone database.

LoadLocation has the following parameters:

* name string
    Name is the name of the location to load.
    The names correspond to names in the [IANA tzdb](https://www.iana.org/time-zones).

Examples:

    loadLocation(name:"America/Denver")
    loadLocation(name:"America/Chicago")
    loadLocation(name:"Africa/Tunis")

**Comment by russorat** [comment] 2020-03-04 06:51
dupe of #406 ?

**Closed** 2024-10-29 01:55 UTC
Labels: duplicate, enhancement, team/query, new function, no-issue-activity
