### ISSUE TITLE
Parser merges two separate statements

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1102] opened 2019-03-28 14:43 UTC
When parsing:

```
not (a and b)
(a or b) and c
```

The parser parses a single statement:

```
unexpected statement -want/+got
            λ({*ast.File}.Body[0].BaseNode.Loc.End):
            	-: "1:13"
            	+: "2:15"
            {*ast.File}.Body[0].BaseNode.Loc.Source:
            	-: "not (a and b"
            	+: "not (a and b)\n(a or b) and c"
            {*ast.File}.Body[0].Expression:
            	-: &ast.UnaryExpression{BaseNode: ast.BaseNode{Loc: s"1:1-1:13"}, Operator: s"not", Argument: &ast.LogicalExpression{BaseNode: ast.BaseNode{Loc: s"1:6-1:13"}, Operator: s"and", Left: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"1:6-1:7"}, Name: "a"}, Right: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"1:12-1:13"}, Name: "b"}}}
            	+: &ast.LogicalExpression{BaseNode: ast.BaseNode{Loc: s"1:1-2:15"}, Operator: s"and", Left: &ast.UnaryExpression{BaseNode: ast.BaseNode{Loc: s"1:1-2:9"}, Operator: s"not", Argument: &ast.CallExpression{BaseNode: ast.BaseNode{Loc: s"1:6-2:9"}, Callee: &ast.LogicalExpression{BaseNode: ast.BaseNode{Loc: s"1:6-1:13"}, Operator: s"and", Left: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"1:6-1:7"}, Name: "a"}, Right: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"1:12-1:13"}, Name: "b"}}, Arguments: []ast.Expression{&ast.ObjectExpression{BaseNode: ast.BaseNode{Loc: s"2:2-2:8"}, Properties: []*ast.Property{&{BaseNode: ast.BaseNode{Loc: s"2:2-2:3"}, Key: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"2:2-2:3"}, Name: "a"}}, &{BaseNode: ast.BaseNode{Loc: s"2:7-2:8"}, Key: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"2:7-2:8"}, Name: "b"}}}}}}}, Right: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"2:14-2:15"}, Name: "c"}}
            {*ast.File}.Body[1->?]:
            	-: &ast.ExpressionStatement{BaseNode: ast.BaseNode{Loc: s"2:2-2:15"}, Expression: &ast.LogicalExpression{BaseNode: ast.BaseNode{Loc: s"2:2-2:15"}, Operator: s"and", Left: &ast.LogicalExpression{BaseNode: ast.BaseNode{Loc: s"2:2-2:8"}, Operator: s"or", Left: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"2:2-2:3"}, Name: "a"}, Right: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"2:7-2:8"}, Name: "b"}}, Right: &ast.Identifier{BaseNode: ast.BaseNode{Loc: s"2:14-2:15"}, Name: "c"}}}
            	+: <non-existent>
```

**Comment by wolffcm** [comment] 2019-04-12 21:50
The issue is that when the parser sees the second `(` it thinks that it's beginning a call.
```
not (a and b) (a or b) and c
              ^
```
So the AST that gets generated for this is:
```
AND(NOT(CALL(AND(a, b), (a: nil))), C) 
```
In other words, it reads `(a and b)` as a callee and `(a or b)` as the arguments.  But in this case the arguments aren't correctly formatted, so it ends up with `(a: nil)`.

I think this is actually an ambiguous case in the grammar.  If we see a `(` we need to do a little more lookahead to determine if we are parsing a call.

Also, we should be returning an error for an incorrectly argument list.

**Comment by nathanielc** [comment] 2019-04-15 15:47
Maybe related to https://github.com/influxdata/influxdb/issues/12205

**Comment by wolffcm** [comment] 2019-04-15 17:08
Here's the course of action I'll take for this issue:
- Update the parser to generate an error for an ill-formatted property list.  This would make it so the above input would fail with a more helpful message.  At that point I'll close this issue.
- See what #1167 teaches us about ambiguities in our grammar.  Maybe injecting semicolons a la Go is the right way to go, or maybe we could become an `LL(3)` grammar, or maybe some other solution would be best.

@nathanielc @jsternberg Does this seem like a reasonable resolution?

**Comment by nathanielc** [comment] 2019-04-15 17:18
@wolffcm SGTM

**Comment by jsternberg** [comment] 2019-04-15 17:20
Those sound good to me too. I don't want us to go down the `LL(3)` grammar without serious consideration, but we do need to add more error checking and so that always sounds good to me.

**Closed** 2019-05-03 17:55 UTC
Labels: breaking, bug
