### ISSUE TITLE
timezone.location.offset always returns 0ns

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/flux#4966] opened 2022-07-07 14:26 UTC
I'm doing a bit of testing with timezones in Flux (hardcoded timestamps are always interpreted as UTC!)
It tuns out that timezone.location always returns 0ns as offset, no matter the timezone:
~~~
import "timezone"
import "array"
option location = timezone.location(name: "America/Los_Angeles")
zone=location.zone
offset=string(v:location.offset)

array.from(rows: [{_time: 2020-01-01T00:00:00Z, _value: zone},
                  {_time: 2020-01-02T00:00:00Z, _value: offset}])
~~~
Open the influxDB data explorer, type above code into the editor and submit...

**Comment by onelson** [comment] 2022-07-07 16:24
I think this is probably a duplicate of #4868. Likely, I think the fix here is going to be some docs improvements.
I didn't do a great job of explaining what came up in discussion on that other issue, but I an try to summarize here.

I don't have a great understanding of _why_ the offset is 0 for named time zones per our implementation, but the piece I was missing was _depending on the point in time the operation is happening on, the offset can be different_. To this end, it makes sense that we'd avoid looking at the fixed offset where ever possible. 

Put another way, it won't not make sense to perform an offset-based calculation using the _current offset_ (based on `now()`) if the calculation is to happen on some date other than today.

For example, if you look at the first and last day of November in `America/Los_Angeles` the offset will be -7 and -8 at either end. Since the actual value of the offset isn't known until you try to perform some operation on a specific date, looking at the `location.offset` field is ill-advised.

**Comment by Kortenbach** [comment] 2022-07-08 15:54
You've got a point there. So it's probably best to use UTC only when querying. Another thing is that, when the docker container is running in UTC you get weird behavior when using the date selector for queries... I set the TZ env var. And now it's fine...

**Comment by onelson** [comment] 2022-07-08 16:09
Many of the functions in the stdlib are "timezone aware" and know to use the `location` option when set. I think the intent is to set the `location` for the script and let functions like `date.truncate()` just "do their thing" without intervention.

**Comment by Kortenbach** [comment] 2022-07-08 17:03
Just setting the location has no effect on query results as far as I can tell. I used "hard coded" time ranges to test. That's why I started investigating the offset in the first place. It would be interesting to see some examples that show the effect of the Timezone option.

**Comment by Kortenbach** [comment] 2022-07-09 17:34
I'm afraid I can't follow you... sorry...

**Comment by Arrgg** [comment] 2022-08-01 08:38
So the today() function only returns UTC time?  Seems to make it kind of useless.

**Closed** 2023-04-18 01:45 UTC
Labels: no-issue-activity
