### ISSUE TITLE
Registration Finalize check for all builtins is failing

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2404] opened 2020-01-17 16:27 UTC
Wild guesses:

* We missed a builtin on the Rust side
* Builtin type changed?
* Something else...

**Comment by nathanielc** [comment] 2020-01-17 16:37
Start here https://github.com/influxdata/flux/blob/master/compile.go#L333

```
go test ./stdlib/...
```

**Comment by jsternberg** [comment] 2020-01-17 16:40
I am not sure how to fix it, but it's probably related to this line: https://github.com/influxdata/flux/blob/bb649ae70ec14d1b85a8f76f2d9d90ebe4a1f0d6/compile.go#L268

This creates a new package with an empty object. With the new way objects are constructed, this is an error. An empty object will always stay an empty object and calling `Set` doesn't help. So we likely have to refactor how packages get created so that it constructs the object as part of the eval rather than what it currently does.

Since an empty object gets created, calls to `Set` probably fail or never happen for the builtin types because the object was already created with no keys.

**Comment by wolffcm** [comment] 2020-01-17 17:58
The error I was seeing looked like this:
```
panic: package has invalid builtins "system": missing builtin values [time], extra builtin values []
goroutine 1 [running]:
github.com/influxdata/flux.FinalizeBuiltIns()
	/Users/cwolff/workspace/github.com/influxdata/flux/compile.go:365 +0x122
github.com/influxdata/flux_test.init.0()
	/Users/cwolff/workspace/github.com/influxdata/flux/spec_test.go:27 +0x20
Process finished with exit code 1
```

Once #2406 is merged, this issue will be easily reproducible on the `feat/use-algo-w` branch by running the test `TestValidatePackageBuiltins`.

**Comment by jsternberg** [comment] 2020-01-17 21:35
I updated the object set to panic when it couldn't find the key which should make what's happening here more obvious. Previously, it was just discarding values that it couldn't set.

**Comment by jsternberg** [comment] 2020-02-03 16:33
We're now finalizing without an error. The interpreter refactor will handle fixing the importer to be able to use the registered values.

**Closed by jsternberg** 2020-02-03 16:33 UTC
Labels: team/query
