### ISSUE TITLE
Add mode() function

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#195] opened 2018-10-29 22:50 UTC
In terms of achieving parity with InfluxQL, the aggregate function mode() is currently missing from the spec. 

https://docs.influxdata.com/influxdb/v1.6/query_language/functions/#mode

While not critical for the technical preview, assume that this should be part of Flux 1.0.

duplicated by #1408

**Comment by nathanielc** [comment] 2019-07-03 19:11
Closing as duplicate of #1408

**Closed by nathanielc** 2019-07-03 19:11 UTC
Labels: enhancement, team/query
