### ISSUE TITLE
Enable Flux to() for 1.x -- using the 2.x /write compatibility API

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#2652] opened 2020-03-19 16:56 UTC
For the 1.x releases of Flux, we've disabled the to() function.  However, with the introduction of the 2.x /write compatibility API to the 1.8.x release, we should be able to remove this restriction.

**Comment by rbetts** [comment] 2020-04-20 18:39
Dupe of: https://github.com/influxdata/influxdb/issues/17790

**Closed by rbetts** 2020-04-20 18:39 UTC
Labels: area/ingestion, enhancement, team/query
