### ISSUE TITLE
Implement FixedZone function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#156] opened 2018-10-19 22:37 UTC
From the SPEC:

FixedZone creates a location based on a fixed time offset from UTC.

FixedZone has the following parameters:

* offset duration
    Offset is the offset from UTC for the time zone.
    Offset must be less than 24h.
    Defaults to 0, which produces the UTC location.

Examples:

    fixedZone(offset:-5h) // time zone 5 hours west of UTC
    fixedZone(offset:4h30m) // time zone 4 and a half hours east of UTC

**Comment by russorat** [comment] 2020-03-04 06:50
dupe of #406 ?

**Closed** 2024-10-29 01:55 UTC
Labels: duplicate, enhancement, team/query, new function, no-issue-activity
