### ISSUE TITLE
join package - left: invalid message

### ISSUE THREAD

**Issue by abalone23** [influxdata/flux#5023] opened 2022-07-25 20:42 UTC
The following query using the new `join` package returns an error:
>runtime error @19:5-24:2: left: invalid message

```js
import "join"

c01 = from(bucket: "telegraf")
  |> range(start: -1m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  |> filter(fn: (r) => r["cpu"] == "cpu0" or r["cpu"] == "cpu1")
  |> keep(columns: ["_value", "_time", "cpu"])
//   |> group(columns: ["cpu"])

c1 = from(bucket: "telegraf")
  |> range(start: -1m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  |> filter(fn: (r) => r["cpu"] == "cpu1")
  |> keep(columns: ["_value", "_time", "cpu"])
//   |> group(columns: ["cpu"])

j = join.left(
    left: c01,
    right: c1,
    on: (l, r) => l.cpu == r.cpu and l._time == r._time,
    as: (l, r) => ({l with v_right: r._value}),
)

j
```
Note that if I explicitly group by `cpu`, which is already grouped, it works fine.

**Comment by scbrickley** [comment] 2022-07-25 20:48
Thanks, @abalone23! I'll start looking into this ASAP.

**Comment by scbrickley** [comment] 2022-07-27 14:34
@abalone23 What environment are you seeing this in? I can't seem to reproduce this in cloud or OSS.

**Comment by abalone23** [comment] 2022-07-27 19:17
I can no longer reproduce this in InfluxDB Cloud Flux `v0.176.0`

**Comment by scbrickley** [comment] 2022-07-27 19:24
Looks like this was resolved in https://github.com/influxdata/flux/pull/5009

**Closed by scbrickley** 2022-07-27 19:24 UTC
Labels: kind/bug, team/query
