### ISSUE TITLE
Panic when group by none after filter

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#41] opened 2018-09-19 19:54 UTC
```
from(bucket: "telegraf")
|> range(start: -20s)
|> filter(fn: (r) => r._measurement == "mem")
|> group(none:true)
```

```
[rsavage@mbp ~/releases/influxdb-1.7.0~n201809180800-0/usr/bin]$ ./influxd

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2018-09-19T19:53:21.703681Z	info	InfluxDB starting	{"log_id": "0Adr9E9l000", "version": "1.7.0~n201809180800", "branch": "master", "commit": "3f917e281a081988cafd2bcba027dd3177cb7ec6"}
2018-09-19T19:53:21.703717Z	info	Go runtime	{"log_id": "0Adr9E9l000", "version": "go1.10.3", "maxprocs": 4}
```

**Comment by jsternberg** [comment] 2018-10-30 14:09
I'm going to return to this today most likely, but I'm getting some lower hanging fruit done first so they are out of the way. If somebody else needs work before I get back to this, feel free to take it.

**Comment by jlapacik** [comment] 2018-10-30 15:36
@russorat I tested the above query, as well as variants of the above, with the new query planner, and was unable to reproduce the panic that you had mentioned. Everything worked perfectly. Please let me know if you are still getting a panic with the new update.

**Comment by jsternberg** [comment] 2018-10-30 16:15
I'm going to close this for now. As mentioned above, if this is still an issue, reopen and we'll look at it immediately.

**Closed by jsternberg** 2018-10-30 16:15 UTC
Labels: bug
