### ISSUE TITLE
Missing macos build support in flux

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#2656] opened 2020-03-19 18:54 UTC
With the work completed in #2245, there is an outstanding task for doing macOS builds. It is not immediately clear how `osxcross` can work into this system, but either we can integrate it with our `Dockerfile_build` file and goreleaser, or it will be a manual process due to licensing restrictions of macOS build libraries.

**Comment by jsternberg** [comment] 2020-03-19 20:18
Duplicate of #2654.

**Closed by jsternberg** 2020-03-19 20:18 UTC
Labels: team/query
