### ISSUE TITLE
Chronograf and CLI give different results for same query

### ISSUE THREAD

**Issue by rbetts** [influxdata/flux#1883] opened 2019-09-17 19:28 UTC
url -i  influxdb:8086/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 6314a668-d97c-11e9-bf6c-000000ffffb0
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.8
X-Request-Id: 6314a668-d97c-11e9-bf6c-000000ffffb0
Date: Tue, 17 Sep 2019 18:53:07 GMT

When I run the same Flux query I get a different result depending on whether I run it in Chronograf or from the CLI.

```
Query:
from(bucket: "telegraf/autogen")
  |> range(start: -5m)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage_user")
  |> filter(fn: (r) => r.cpu == "cpu-total")
  |> window(every: 10s)
  |> group(columns: ["host"])
```

 Result from Chronograf:
 ```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#group,false,false,false,false,false,false,false,false,false,true
#default,_result,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,cpu,host
,,0,2019-09-17T18:37:30Z,2019-09-17T18:37:40Z,2019-09-17T18:37:30Z,0.037617554859119606,usage_user,cpu,cpu-total,influxdb
,,0,2019-09-17T18:37:40Z,2019-09-17T18:37:50Z,2019-09-17T18:37:40Z,0.03132243312655841,usage_user,cpu,cpu-total,influxdb
,,0,2019-09-17T18:37:50Z,2019-09-17T18:38:00Z,2019-09-17T18:37:50Z,0.216239932307475,usage_user,cpu,cpu-total,influxdb
```

Result from CLI
```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string
#group,false,false,false,false,false,false,false,false,false,true
#default,_result,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,cpu,host
,,0,2019-09-17T18:34:10Z,2019-09-17T18:34:20Z,2019-09-17T18:34:10Z,16.43285315251731,usage_user,cpu,cpu-total,influxdb
,,0,2019-09-17T18:34:10Z,2019-09-17T18:34:20Z,2019-09-17T18:34:10Z,22.18749999991953,usage_user,cpu,cpu0,influxdb
,,0,2019-09-17T18:34:10Z,2019-09-17T18:34:20Z,2019-09-17T18:34:10Z,18.477157360449986,usage_user,cpu,cpu1,influxdb
,,0,2019-09-17T18:34:10Z,2019-09-17T18:34:20Z,2019-09-17T18:34:10Z,14.900000000000091,usage_user,cpu,cpu10,influxdb
```

**Comment by jsternberg** [comment] 2019-09-18 21:27
@rbetts have you ensured that your repl is completely up to date? I noticed that the CLI did not filter the cpu tag.

The CLI uses the repl compiler and the repl compiler doesn't seem to use any planner options so it might not be using any of the planner rules. We should check that too.

**Comment by wolffcm** [comment] 2019-09-26 21:02
Note, this happened running Flux in InfluxDB 1.7.8.

I can't reproduce this using the 1.7.8 docker image for influxdb.  The Chronograf result looks correct, and the CLI result is wrong.  I tried executing from the CLI in a couple ways:
- using the REPL via `influx -type flux`
- using `curl` with `Content-Type: application/vnd.flux`

Both ways seem to to produce a correct result, and I didn't see the mis-filtering of the `cpu` column.

**Comment by wolffcm** [comment] 2019-10-07 16:50
@dp1140a I think this issue originated with you?  I'm going to close it as not reproducible, but if you see it again or have any additional context, we can reopen it.

**Closed by wolffcm** 2019-10-07 16:50 UTC
Labels: bug, team/query, wrong answer
