### ISSUE TITLE
flux results |> limit |> group not working as expected

### ISSUE THREAD

**Issue by rostero1** [influxdata/flux#775] opened 2018-08-13 19:17 UTC
We are testing out influxdb and flux.  I have a measurement with a `userId` and `favorite` tag and a favorite `field`.  I want to get the last favorite field for each userId and then count each favorite.  The current flux syntax claims `|>` is a pipe-forward operator; as such, I'm assuming order doesn't matter and that I can continue piping output to input until I get my desired result.

Why does this query produce `timeSrc column \"_stop\` does not exist.

```
from(db: "testdb")
  |> range($range)
  |> filter(fn:(r) => r._measurement == "favoriteChange")
  |> group(by: ["userId"])
  |> sort(cols: ["_time"], desc: true)
  |> limit(n: 1)
  |> group(by: ["favorite"])
  |> count()
```

It produces when I don't try to count the favorites:

```
from(db: "testdb")
  |> range($range)
  |> filter(fn:(r) => r._measurement == "favoriteChange")
  |> group(by: ["userId"])
  |> sort(cols: ["_time"], desc: true)
  |> limit(n: 1)
```

**Comment by aanthony1243** [comment] 2019-07-05 17:12
hi, this is a bit hard to reproduce without more information.   Can you give sample output for: 

```
from(db: "testdb")
  |> range($range)
  |> filter(fn:(r) => r._measurement == "favoriteChange")
  |> group(by: ["userId"])
  |> sort(cols: ["_time"], desc: true)
  |> limit(n: 1)
```

if not actual data, an example table header would be useful as well.

**Comment by affo** [comment] 2019-07-08 10:23
The issue is very old. I checkout to commit `99db5d1adf97b73c6116bea7721b14db729c9203` on the 13th of August 2018.

Aggregates looked for the presence of a time column. They don't do that anymore.

`AggregateConfig` was:

```go
type AggregateConfig struct {
	Columns []string `json:"columns"`
	TimeSrc string   `json:"time_src"`
	TimeDst string   `json:"time_dst"`
}
```

Now it is:

```go
type AggregateConfig struct {
	plan.DefaultCost
	Columns []string `json:"columns"`
}
```

@rostero1 I don't think you would be able to reproduce that bug anymore.

**Comment by aanthony1243** [comment] 2019-07-08 14:26
didn't see that.  I think we can close this.

**Closed by aanthony1243** 2019-07-08 14:26 UTC
Labels: bug, team/query
