### ISSUE TITLE
bug in package formatting, and in options getting.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/flux#779] opened 2019-01-09 16:02 UTC
```go
// This test shows two bugs, one in format and one in options getting 
// when an option is commented out.
func TestParse(t *testing.T) {
	script := `option task = {cron:"* * * * *", name: "foo"}
            
	from(bucket: "x")
		|> range(start: -1h)`

	parsed := parser.ParseSource(script)
	script2 := ast.Format(parsed)
	t.Log(script2)

	inter := flux.NewInterpreter()
	if err := flux.Eval(inter, script2); err != nil {
		t.FailNow()
	}

	// pull options from interpreter
	task := inter.Option("task")
	if task == nil {
		t.FailNow()
	}
	optObject := task.Object()
	_, ok := optObject.Get("name")
	if !ok {
		t.FailNow()
	}

	_, cronOK := optObject.Get("cron")
	_, everyOK := optObject.Get("every")
	if cronOK && everyOK {
		t.FailNow()
	}
}
```

A workaround is to use `script2 := ast.Format(parsed.Files[0])` instead of 	`script2 := ast.Format(parsed)` for the first bug, but the second doesn't have a workaround.

**Comment by affo** [comment] 2019-01-09 16:51
The format bug was fixed in a previous commit of Flux and will ship with the next release.

@docmerlin for the option getting one, do you think it is a bug if the interpreter doesn't interpret options in comments?

**Comment by docmerlin** [comment] 2019-01-09 22:39
@affo that isn't the problem.  The problem was that it was assuming that both options where set when only one was set in a comment, so something strange was happenening.  Nether of them should have been set (as it was in a comment due to the aforementioned bug), but both where.

**Comment by affo** [comment] 2019-01-10 08:08
I see. Can you file a specific issue for that?

I close this one because it is related to 2 bugs, one of which is not a bug indeed.

**Closed by affo** 2019-01-10 08:08 UTC
