### ISSUE TITLE
Cannot unify error when using union with mismatching columns

### ISSUE THREAD

**Issue by dangilkerson** [influxdata/flux#2453] opened 2020-02-04 16:03 UTC
Error: cannot unify (<-tables:[t3954], interval:duration, n:int, seasonality:int, ?column:string, ?timeColumn:string, ?withFit:bool) -> [t3955] with (<-:[{_field:string | City:string | t3971}], interval:duration, n:int) -> t3904
```
option v = {timeRangeStart: 2019-10-19T20:58:16.263Z, timeRangeStop: 2019-12-27T20:58:16Z}
pastData = from(bucket: "Buck")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  
forecast =  from(bucket: "Buck")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> holtWinters(n: 10, interval: 1d)
  
union(tables: [pastData, forecast])
```

**Comment by nathanielc** [comment] 2020-02-05 21:27
@dangilkerson Turns out that the error above is because of a bug in holt winters. I have a fix for it here https://github.com/influxdata/flux/pull/2465 

I was pretty sure that there were other `union` related bugs though. Could you maybe share a different `union` error so we can investigate?

**Comment by dangilkerson** [comment] 2020-02-05 21:33
All the union ones I have with errors call holtWinters

**Comment by jlapacik** [comment] 2020-02-05 21:37
That sounds like good news

**Comment by jlapacik** [comment] 2020-02-06 17:09
See https://github.com/influxdata/flux/pull/2472 for a test case confirming union's intended behavior. I think we should close this issue.

**Closed** 2020-02-11 00:31 UTC
Labels: team/qa, team/query
