### ISSUE TITLE
to function should have better error messaging

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#874] opened 2019-01-16 21:41 UTC
when using the to function, i saw the following error message. i believe you can also use org name instead if id.

```
➜  darwin git:(master) ✗ ./influx query --org-id 0342065389978000 'from(bucket: "default")  |> range(start: -30d)  |> to(bucket:"new_bucket")'
error calling function "to": missing required keyword argument "orgID"
```

**Comment by nathanielc** [comment] 2019-06-24 20:26
This is a duplicate of #247

**Closed by nathanielc** 2019-06-24 20:26 UTC
Labels: epic/lang-simplify
