### ISSUE TITLE
*immutable.SortedMap does not implement immutable.Comparer (missing Compare method)

### ISSUE THREAD

**Issue by doivosevic** [influxdata/flux#3411] opened 2021-01-02 22:47 UTC
I'm trying to go get influxdb. I get stuck at 
```

go get github.com/influxdata/influxdb
# github.com/influxdata/flux/values
../../.gvm/pkgsets/go1.15.6/global/src/github.com/influxdata/flux/values/dict.go:339:25: cannot use immutable.NewSortedMap(dictComparer(dictType)) (type *immutable.SortedMap) as type immutable.Comparer in argument to immutable.NewSortedMapBuilder:
        *immutable.SortedMap does not implement immutable.Comparer (missing Compare method)
```

how is the build marked as passing? I'm using go 1.15.6

**Comment by jsternberg** [comment] 2021-01-04 16:46
I'm honestly not sure what's going on here. It seems like the upstream tag may have changed contents. When I go to [here](https://github.com/benbjohnson/immutable/compare/v0.2.1...v0.3.0) to compare the versions, I see the breaking change. We're using the API for v0.3.0 and using v0.2.1 would not work even though we have v0.2.1 in our `go.mod`.

But when I go to the actual source code for [v0.2.1](https://github.com/benbjohnson/immutable/blob/v0.2.1/immutable.go#L1555) I see the proper code I would expect. I am not sure why these are different. I'll up our version to v0.3.0 as that's the latest and the version that's compatible with our code and then ask upstream if something may have happened to confuse go modules.

Since our CI caches dependencies, it may have cached the dependency before whatever you are running into happened. This would be why the build is marked as passing. The build passes on my local machine because I have the second version of v0.2.1 cached locally on my machine too.

Thanks for this bug report. I'll get it fixed soon.

**Comment by jsternberg** [comment] 2021-01-04 21:13
I took another look at this and the current build should work unless there's something else in your work environment. It seems that error pops up because `NewSortedMapBuilder` had its signature changed between `v0.2.1` and `v0.3.0`. We use the `v0.2.1` version and our usage is consistent with that. Go modules will choose the oldest version of a dependency that it can when it attempts to compile. Since influxdb doesn't use that dependency, it uses the one selected by flux which is `v0.2.1`. This is the reason why builds seem to work for us.

If you ended up somehow upgrading that dependency to the `v0.3.0` version, such as by running something like `go get -u` (which updates all of the dependencies), it might have upgraded that dependency to the most recent.

Since we don't want to end up on an old version and the fix is minor, I'm still going to upgrade our own usage to `v0.3.0` so that this is easier.

**Comment by Kungitoo** [comment] 2021-01-05 09:46
I've tried running this from a clean machine so there is nothing from before which could influence this. I'll try again after your PR. Is the PR going to put the changes in master as well?

**Comment by lukekim** [comment] 2021-09-23 03:03
I get the same thing, even on v0.131.0:

```bash
go: downloading github.com/influxdata/flux v0.131.0
# github.com/influxdata/flux/values
../../go/pkg/mod/github.com/influxdata/flux@v0.131.0/values/dict.go:339:25: cannot use immutable.NewSortedMap(dictComparer(dictType)) (type *immutable.SortedMap) as type immutable.Comparer in argument to immutable.NewSortedMapBuilder:
        *immutable.SortedMap does not implement immutable.Comparer (missing Compare method)
```

Also confirmed go.mod is requiring `github.com/benbjohnson/immutable v0.3.0 // indirect`

**Comment by lukekim** [comment] 2021-09-23 03:45
It looks like the PR never made it to master. The v0.131.0 release includes the old broken code, so if the module is upgraded to v0.3.0 the build breaks.

**Comment by lukekim** [comment] 2021-09-23 03:54
Submitted a PR to bring #3413 to master: https://github.com/influxdata/flux/pull/4072.

**Closed** 2023-11-15 01:41 UTC
Labels: no-issue-activity
