### ISSUE TITLE
unsupported binary expression string > float

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#4084] opened 2021-09-27 20:33 UTC
I was trying this on InfluxDB Cloud today. My expectation is that these two queries should be identical and produce results. I have verified that the `_value` column is in fact a float.

The following query:

```
import "influxdata/influxdb/sample"

sample.data(set: "usgs")
  |> filter(fn: (r) => r._field == "mag" and r._measurement == "earthquake" and r._value > 4.0)
```

returns the error:

`runtime error @4:6-4:96: filter: cannot compile @ 4:17-4:95: unsupported binary expression string > float`

but this query:

```
import "influxdata/influxdb/sample"

sample.data(set: "usgs")
  |> filter(fn: (r) => r._field == "mag" and r._measurement == "earthquake")
  |> filter(fn: (r) => r._value > 4.0)
```

succeeds with no issues.

**Comment by onelson** [comment] 2022-01-28 22:22
We don't have fix for this today, but wanted to share that the problem is at least better understood now:

https://github.com/influxdata/flux/issues/4378#issuecomment-1024688715

In your first query, you've effectively done the transformation that the `MergeFiltersRule` would have performed when starting from the 2nd query.

Seems like in order to make the two queries equivalent, we'd have to overhaul how the type checking happens at runtime, which is likely a big lift.

**Closed** 2023-08-15 01:35 UTC
Labels: kind/bug, no-issue-activity
