### ISSUE TITLE
Use of one of my custom functions in a map fails

### ISSUE THREAD

**Issue by nisley** [influxdata/flux#2387] opened 2020-01-14 22:30 UTC
I can run and return the value from my custom function getValueInsideTimerange()

When I use it in a map I get
>panic: interface conversion: interface {} is nil, not lang.ExecutionDependencies
![image](https://user-images.githubusercontent.com/1389799/72388218-33ea8780-36da-11ea-8497-9d0b0bdbc6fe.png)

```
getValueInsideTimerange = (earlierTime, laterTime) => {
	abc = from(bucket: "NOAA")
          |> range(start: time(v: 1578833173620), stop: time(v: 1578833173631) )
          |> filter(fn: (r) => r._measurement == "data")
          |> tableFind(fn: (key) => key._field == "speed")
          |> getRecord(idx: 0)
          return abc._value
}

from(bucket: "NOAA")
  |> range(start: -5h)
  |> filter(fn: (r) => r._measurement == "intervals")
  |> map(fn: (r) => 
          ({
            time: r._time,
            datad: float(v: getValueInsideTimerange(earlierTime: 1578833173620, laterTime: 1578833173631) )
          })
        )
```

**Comment by rockstar** [comment] 2020-01-15 16:36
Here's a stack trace, from slack.

```2020-01-15T16:29:41.320891Z	info	Dispatcher panic	{"log_id": "0KLbyqLW000", "service": "storage-reads", "component": "dispatcher", "error": "panic: interface conversion: interface {} is nil, not lang.ExecutionDependencies"}
goroutine 102350 [running]:
runtime/debug.Stack(0xc013a484e0, 0x69ac800, 0x5ac6155)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc013a48540)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/dispatcher.go:81 +0x192
panic(0x57d9dc0, 0xc013d17230)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/influxdata/flux/lang.GetExecutionDependencies(...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/lang/dependencies.go:27
github.com/influxdata/flux/stdlib/universe.tableFindCall(0x69ef940, 0xc013a4b0e0, 0x6a21ea0, 0xc013a8b2c0, 0x40, 0x5a87c60, 0xc013cda201, 0xc013d00cc0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/stdlib/universe/table_fns.go:91 +0xd13
github.com/influxdata/flux/values.(*function).Call(0xc00040eae0, 0x69ef940, 0xc013a4b0e0, 0x6a21ea0, 0xc013a8b2c0, 0xc013cda0c0, 0x5ab53ed, 0x6, 0x6a08140)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/values/function.go:115 +0x52
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0xc011a8e770, 0x6a17ba0, 0xc013cda0c0, 0x0, 0xc00003c000, 0x59b2d00, 0x5a31340)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:651 +0x504
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0x6a08140, 0xc011a8e770, 0x6a17ba0, 0xc013cda0c0, 0x6a1d580, 0xc013ca9280, 0x0, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:321 +0x2321
github.com/influxdata/flux/interpreter.(*Interpreter).doArguments(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0xc011a8e540, 0x6a17ba0, 0xc013cda0c0, 0x5ab3ab9, 0x5, 0x6a08140, 0xc011a8e770, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:693 +0x6d5
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0xc011a8e5b0, 0x6a17ba0, 0xc013cda0c0, 0xc013aead01, 0x56da8a0, 0xc0001440a0, 0x8525201)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:627 +0x371
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0x6a08140, 0xc011a8e5b0, 0x6a17ba0, 0xc013cda0c0, 0x5a42b80, 0xc013ca91e0, 0x80a02e0, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:321 +0x2321
github.com/influxdata/flux/interpreter.(*Interpreter).doVariableAssignment(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0xc012860360, 0x6a17ba0, 0xc013cda0c0, 0x30, 0x58d4000, 0x5a14101, 0xc013cda0c0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:274 +0x7d
github.com/influxdata/flux/interpreter.(*Interpreter).doStatement(0xc000987220, 0x69ef940, 0xc013a4b0e0, 0x6a03d60, 0xc012860360, 0x6a17ba0, 0xc013cda0c0, 0x203004, 0x30, 0x5a14100, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:158 +0x74d
github.com/influxdata/flux/interpreter.function.doCall(0xc012860420, 0x6a17ba0, 0xc0128b3470, 0xc009b76ff0, 0xc0139ee390, 0xc0139ee3c0, 0xc000987220, 0x69ef940, 0xc013a4b0e0, 0x6a1e660, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:862 +0x684
github.com/influxdata/flux/interpreter.function.Call(0xc012860420, 0x6a17ba0, 0xc0128b3470, 0xc009b76ff0, 0xc0139ee390, 0xc0139ee3c0, 0x0, 0x69ef940, 0xc013a4b0e0, 0x6a21ea0, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/interpreter/interpreter.go:810 +0x128
github.com/influxdata/flux/compiler.(*callEvaluator).Eval(0xc013cc1c50, 0x69ef940, 0xc013a4b0e0, 0x6a190a0, 0xc013c83900, 0x9f676d0, 0xc000fc5400, 0x9f676d0, 0x0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:598 +0x190
github.com/influxdata/flux/compiler.eval(...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:104
github.com/influxdata/flux/compiler.(*objEvaluator).Eval(0xc013ca8ee0, 0x69ef940, 0xc013a4b0e0, 0x6a190a0, 0xc013c83900, 0x0, 0x6a10c60, 0x57865a0, 0xc013cd2c78)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:227 +0x190
github.com/influxdata/flux/compiler.(*callEvaluator).Eval(0xc013cc1cb0, 0x69ef940, 0xc013a4b0e0, 0x6a190a0, 0xc013c83900, 0x6a1d580, 0xc013ca8fe0, 0x0, 0x0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:590 +0x6c
github.com/influxdata/flux/compiler.eval(...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:104
github.com/influxdata/flux/compiler.(*objEvaluator).Eval(0xc013ca8e80, 0x69ef940, 0xc013a4b0e0, 0x6a190a0, 0xc013c83900, 0xc013c83900, 0x6a21ea0, 0xc013a485a0, 0x0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:227 +0x190
github.com/influxdata/flux/compiler.eval(...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:104
github.com/influxdata/flux/compiler.compiledFn.Eval(0x69cbdc0, 0xc013ca8e80, 0x6a088c0, 0xc013cd0280, 0x6a190a0, 0xc013c83900, 0x69ef940, 0xc013a4b0e0, 0x6a21ea0, 0xc013a485a0, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/compiler/runtime.go:71 +0xbb
github.com/influxdata/flux/execute.(*rowFn).eval(0xc013a48600, 0x69ef940, 0xc013a4b0e0, 0x0, 0x6a15c20, 0xc00a6c68c0, 0x0, 0x0, 0xc013aeb9f8, 0x400ecd6, ...)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/row_fn.go:173 +0x2ae
github.com/influxdata/flux/execute.(*RowMapFn).Eval(0xc013a48600, 0x69ef940, 0xc013a4b0e0, 0x0, 0x6a15c20, 0xc00a6c68c0, 0x0, 0x4004d33, 0xc013aeb9f8, 0x4016883)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/row_fn.go:253 +0x75
github.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process.func1(0x6a15c20, 0xc00a6c68c0, 0x1, 0x38)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/stdlib/universe/map.go:173 +0x2cc
github.com/influxdata/influxdb/storage/reads.(*table).do(0xc011de1800, 0xc013cd0380, 0xc013aebc10, 0x0, 0x0)
	/Users/nisely/Documents/projects/influxbuilds/influxdb/storage/reads/table.go:81 +0xb6
github.com/influxdata/influxdb/storage/reads.(*floatTable).Do(0xc011de1800, 0xc013cd0380, 0xc00a55f100, 0x7)
	/Users/nisely/Documents/projects/influxbuilds/influxdb/storage/reads/table.gen.go:77 +0x5a
github.com/influxdata/flux/stdlib/universe.(*mapTransformation).Process(0xc013a0dec0, 0x4d5eccd93a5f1dca, 0xb8e093295a108e, 0x1330ee70, 0xc011de1800, 0x4086201, 0x8540f00)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/stdlib/universe/map.go:170 +0x135
github.com/influxdata/flux/execute.processMessage(0x69ef940, 0xc013a4b0e0, 0x69f9400, 0xc013a0dec0, 0x69cc100, 0xc013a43f40, 0xc0020bae9a, 0xc00227d200, 0xc0020baef8)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/transport.go:206 +0x2d6
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc013a48660, 0x69ef940, 0xc013a4b0e0, 0xa)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/transport.go:159 +0xc6
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc013a48540, 0x69ef940, 0xc013a4b0e0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/dispatcher.go:132 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc013a48540, 0x69ef940, 0xc013a4b0e0)
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/dispatcher.go:86 +0xcd
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/Users/nisely/go/pkg/mod/github.com/influxdata/flux@v0.58.0/execute/dispatcher.go:63 +0x7e```

**Comment by nisley** [comment] 2020-01-15 16:37
Technically, for the test that creates the stacktrace this line:
datad: float(v: getValueInsideTimerange(earlierTime: timeBeforeCall, laterTime: timeAfterCall) )

is this:
datad: float(v: getValueInsideTimerange(earlierTime: 1578833173620, laterTime: 1578833173631) )

**Comment by sanderson** [comment] 2020-01-15 16:51
@nisley I don't know that this is the cause of the panic, but just something I noticed – in your custom function definition, you don't use any of the specified parameters. The time values are hard-coded. I think it should look like this:

```js
getValueInsideTimerange = (earlierTime, laterTime) => {
	abc = from(bucket: "NOAA")
          |> range(start: time(v: earlierTime), stop: time(v: laterTime) )
          |> filter(fn: (r) => r._measurement == "data")
          |> tableFind(fn: (key) => key._field == "speed")
          |> getRecord(idx: 0)
          return abc._value
}
```

**Comment by nisley** [comment] 2020-01-15 17:08
> @nisley I don't know that this is the cause of the panic, but just something I noticed – in your custom function definition, you don't use any of the specified parameters. The time values are hard-coded. I think it should look like this:
> 
> ```js
> getValueInsideTimerange = (earlierTime, laterTime) => {
> 	abc = from(bucket: "NOAA")
>           |> range(start: time(v: earlierTime), stop: time(v: laterTime) )
>           |> filter(fn: (r) => r._measurement == "data")
>           |> tableFind(fn: (key) => key._field == "speed")
>           |> getRecord(idx: 0)
>           return abc._value
> }
> ```

Yes, I was trying to eliminate as many variables as possible.

**Comment by giter** [comment] 2020-01-21 03:03
+1 the same problem with influxdb v1.7.9

from(bucket: "rural")
  |> range(start: -15m)
  |> filter(fn:(r) => r._measurement == "raw" and r._field == "value" and r.id == "5d5627b9c334d20001e751b9")
  |> tableFind(fn: (key) => key._field == "id")
  |> getRecord(idx: 0)

**Comment by sanderson** [comment] 2020-01-21 17:26
@giter, The root of the problem lies in that, currently, you cannot execute another query within the context of `map()`. Mapped values must be static. The Flux team is aware of this and have put adding the ability to query within `map()` on their roadmap.

**Comment by adriandt** [comment] 2020-02-21 14:46
Also have an issue inside of a filter. This is a problem on 1.X only. Works fine on 2.0.
```
device,deviceId="device1" deviceName="device1Name",siteId="site1"
device,deviceId="device2" deviceName="device2Name",siteId="site2"
site,siteId="site1" siteName="Oslo"
site,siteId="site2" siteName="Bergen"
site,siteId="site3" siteName="London"
```
Query:
```
d = from(bucket: "db/autogen")
  |> range(start: -12h)
  |> filter(fn: (r) => r._measurement == "device")
  |> tableFind(fn: (key) => key._field == "siteId")
  |> getRecord(idx: 0)

from(bucket: "db/autogen")
  |> range(start: -12h)
  |> filter(fn: (r) => r._measurement == "site" and r.siteId == d.siteId)
```

Results in:
```
panic: interface conversion: interface {} is nil, not influxdb.Dependencies
```
Note that the above has a few errors. It won't produce results. To fix the quotes have to be removed from the line protocol keys and the final filter clause must be `r.siteId == d._value`.

**Comment by adriandt** [comment] 2020-02-24 10:39
Looks like a dependeny injection failure. 

```
panic: interface conversion: interface {} is nil, not lang.ExecutionDependencies

goroutine 1 [running]:
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/lang.GetExecutionDependencies(...)
	/Users/thurston/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/lang/dependencies.go:27
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/universe.tableFindCall(0x280a1a0, 0xc0000cc000, 0x2823f00, 0xc0005da440, 0x40, 0x1c587a0, 0xc0005dc501, 0xc0008cd080)
	/Users/thurston/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/stdlib/universe/table_fns.go:91 +0xd1b
github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/values.(*function).Call(0xc00039ebd0, 0x280a1a0, 0xc0000cc000, 0x2823f00, 0xc0005da440, 0xc000430750, 0x1c70158, 0x6, 0x2814600)
	/Users/thurston/go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/values/function.go:115 +0x52
...
```

**Comment by mcassaniti** [comment] 2020-02-25 04:37
@sanderson I can confirm with something like the below in the InfluxDB v2 REPL that the issue can be triggered without map. This is Flux version 0.59.5

```
// Returns actual data
data = from(bucket: "ts")
  |> range(start: -15m)
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_active")
  |> last()

// Get the first table
data |> tableFind(fn: (key) => 1 == 1)
```

Partial traceback
```
panic: interface conversion: interface {} is nil, not lang.ExecutionDependencies

goroutine 1 [running]:
github.com/influxdata/flux/lang.GetExecutionDependencies(...)
        /go/pkg/mod/github.com/influxdata/flux@v0.59.5/lang/dependencies.go:27
github.com/influxdata/flux/stdlib/universe.tableFindCall(0x2455ce0, 0xc000040050, 0x247b100, 0xc000b50de0, 0xc000b81008, 0x38, 0xc00072bf01, 0xc0005be240)
        /go/pkg/mod/github.com/influxdata/flux@v0.59.5/stdlib/universe/table_fns.go:91 +0xd13
github.com/influxdata/flux/values.(*function).Call(0xc00040f8f0, 0x2455ce0, 0xc000040050, 0x247b100, 0xc000b50de0, 0xc000b37dd0, 0x16315e2, 0x6, 0x2468800)
        /go/pkg/mod/github.com/influxdata/flux@v0.59.5/values/function.go:115 +0x52
github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc000662910, 0x2455ce0, 0xc000040050, 0xc0003f4310, 0x2472f20, 0xc000b37dd0, 0x30, 0x14d61c0, 0xc000afbe01, 0xc00072b320)
        /go/pkg/mod/github.com/influxdata/flux@v0.59.5/interpreter/interpreter.go:651 +0x504
github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc000662910, 0x2455ce0, 0xc000040050, 0x24685c0, 0xc0003f4310, 0x2472f20, 0xc000b37dd0, 0x0, 0x1, 0x4, ...)
        /go/pkg/mod/github.com/influxdata/flux@v0.59.5/interpreter/interpreter.go:321 +0x2321
```

Looking at [GetExecutionDependencies](https://github.com/influxdata/flux/blob/b12a6fe0684fdaa6339397ec7e7bb6d942040676/lang/dependencies.go#L26-L28) suggests that the value being returned is nil, and there is no checking of an error. See the documentation for Value from the [Go context package](https://golang.org/src/context/context.go#L105). I may also have absolutely no idea what I'm talking about in which case I wouldn't mind some educating.

**Comment by adriandt** [comment] 2020-02-25 14:05
If experiencing this issue, switch from executing in the repl to the passing the entire query to the server using the HTTP API. 

As @sanderson mentioned, and as I now understand, this issue is due to some current design constraints that prevent us from sending stream results (eg via tableFind) to a variable that is used in a map or filter. This is a problem in the repl only.

**Comment by mcassaniti** [comment] 2020-02-25 21:33
@adriandt Thanks for the feedback. I'll see where I get to with the API.

**Comment by adriandt** [comment] 2020-03-11 07:55
Closing this as we now have a more graceful failure.

Broader issue is that tableFind must have an execution context and in the repl it sometimes does not.

https://github.com/influxdata/influxdb/issues/13976

**Closed by adriandt** 2020-03-11 07:55 UTC
