### ISSUE TITLE
Remove column parameters from Flux function "range"

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2253] opened 2019-12-06 19:06 UTC
The `range` function has a few seldom-used parameters:
- `timeColumn` defaults to `_time`
- `startColumn` defaults to `_start`
- `stopColumn` defaults to `_stop`

These parameters make it hard to map the input row type to the output row type and break type inference, so the type is
```
                    forall [t0, t1, t2, t3] where t0: Row, t3: Row (
                        <-tables: [t0],
                        start: t1,
                        ?stop: t2,
                        ?timeColumn: string,
                        ?startColumn: string,
                        ?stopColumn: string
                    ) -> [t3]
```

We should remove these parameters so the type can be
```
                    forall [t0, t1, t2] where t0: Row (
                        <-tables: [t0],
                        start: t1,
                        ?stop: t2,
                    ) -> [{_start: time | _stop: time | t0}]
```
Question: what should the behavior be if `_start` and `_stop` already exist?

**Comment by jlapacik** [comment] 2019-12-06 19:58
Note that record labels are scoped so the input records to `range` may have `_start` and `_stop` columns. In that case the input type might look something like this:

    {_start: time | _stop: time | t0}

And the output type would look like this:

    {_start: time | _stop: time | _start: time | _stop: time | t0}

**Comment by nathanielc** [comment] 2019-12-06 20:43
I don't think we should remove the arguments. rather we should use the `label` type for them. For now we can treat them as strings. The pattern of specifying the column names as arguments is very common and not unique to `range`. We will need to solve for that pattern. See https://github.com/influxdata/flux/issues/1122

Alternatively we could remove all of theses column arguments and require that the `rename` operation is used for data that doesn't conform to the expected record type. But require is going to need to understand something similar to label types as well. Thoughts?

**Comment by jlapacik** [comment] 2019-12-06 21:30
We don't have an issue proposing an implementation yet, but any implementation of label types is going to require some form of AST preprocessor. In my opinion adding functionality to an AST preprocessor should be seen as a high barrier to entry as it is a deliberate attempt to get around the type system.

I think `keep` and `drop` are good candidates for label types as they reduce the syntax needed to express the same operation via a call to `map`.

`range` and most other functions are not good candidates in my opinion. Flux is a verbose language by design, however we should try to reduce verbosity where it is not required. I'm all for replacing these column arguments with default labels as part of the type signature. Not only does it allow type inference to correctly infer the types of these functions without the help of an AST preprocessor, but most importantly it simplifies the API for users.

**Comment by nathanielc** [comment] 2019-12-06 22:39
>  I'm all for replacing these column arguments with default labels as part of the type signature.

I am not sure I understand what this means? Can you provide an example?

I agree, `keep` and `drop` make sense but the other `column` arguments are not as useful.

**Comment by jlapacik** [comment] 2019-12-09 15:57
In the example that Chris gave, he's removing `timeColumn`, `startColumn`, and `stopColumn` and instead representing those arguments using the type signature:

    forall [t0, t1, t2] where t0: Row (
        <-tables: [{_time: time | t0}],
        start: t1,
        ?stop: t2,
    ) -> [{_start: time | _stop: time | _time: time | t0}]

I prefer this way vs making the `timeColumn`, `startColumn`, and `stopColumn` label types.

**Comment by jlapacik** [comment] 2020-07-02 18:56
We seem to be converging to the following type signature:
```
forall [t0, t1] where t0: Timeable (
    <-tables: [{_time: time | t0}],
    start: t1,
    ?stop: t1,
) -> [{_start: time | _stop: time | _time: time | t0}]
```
where `Timeable` is a constraint representing duration/time types.

One final question I have is does it make sense for `stop` to be `Timeable`, or should we consider restricting `stop` to be only of type time? In particular, if we are going to change the function signature, do we want to support the following use cases?

```
from(bucket: "b") |> range(start: -2d, stop: -1d)
from(bucket: "b") |> range(start: 1970-01-01T00:00:00Z, stop: 1d)
```

**Comment by nathanielc** [comment] 2020-08-20 15:54
DOD:
- Check query logs to validate this behavior is unused
- The range function no longer has return type polymorphism
- Updated in SPEC with new type signature
- Update inform docs team that the behavior is breaking please use `BREAKING CHANGE` in the commit message for this change

**Comment by adrian-thurston** [comment] 2020-09-03 16:28
Closed by https://github.com/influxdata/flux/pull/3151

**Closed** 2020-09-03 17:59 UTC
Labels: breaking, team/query
