### ISSUE TITLE
Allow function default arguments to be generalizable

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3629] opened 2021-04-19 18:11 UTC
At the current moment, type inference for function arguments will take on the exact type of the default argument. This causes two problems.

1. If we want a function to have a default argument, but still work in a duck-typed way, this is not possible.

```
aggregateWindow = (tables=<-, window={every: 1m}, fn) => tables
    |> window(every: window.every)
    |> fn()
    |> window(every: inf)

aggregateWindow(
    // this will cause a type error because window does not directly match
    // the default, but this would be ok if the default didn't exist
    window: {every: 5m, period: 1m},
    fn: sum,
)
```

2. If a builtin function takes in a generic type, such as `Timeable`, you cannot forward the default argument from a wrapper function.

```
// wrapper around from |> range
select = (bucket, start, stop=now()) => from(bucket) |> range(start, stop)

// error because now() is a time, not a duration
select(bucket: "mybucket", start: -12h, stop: -1h)
```

The reason for this is because we use function default arguments to determine the type of the function and when they are used this way they must resolve to monotypes to be decidable. On the other hand, we could take a different approach to this. If we did not use the default arguments to determine the type of the function and, instead, just verified that the type of the function argument would be valid if it were used with the generalized polytype, we could allow default arguments to be parameterized.

This would end up being the equivalent of this with the current algorithm:

```
select = (bucket, start, stop) => from(bucket) |> range(start, stop)

// this works now because start and stop were determined as timeable instead of time
select(bucket: "mybucket", start: -12h, stop: -1h)
select(bucket: "mybucket", start: -12h) // type inference implicitly inserts stop=now() at the call site instead
```

Although instead of implicitly inserting the default argument at call sites, we would ensure the default argument would work if it were to be the default and then the runtime would still be what handles the default arguments.

**Comment by nathanielc** [comment] 2021-09-16 20:42
This is a duplicate of #3461 Closing in favor of that issue.

**Closed by nathanielc** 2021-09-16 20:42 UTC
Labels: team/query
