### ISSUE TITLE
Encapsulate series cardinality query

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3131] opened 2020-08-18 16:57 UTC
Encapsulate this query (or another) as a way of getting the series cardinality for a stream.

```
|> count() |> group() |> count()
```

The `count()` returns exactly one row and requires it to always be the same type. The group then groups those together and counts them. This pattern works for determining the exact cardinality of any query.

**Comment by jsternberg** [comment] 2020-08-18 16:59
Another option that might be friendlier to storage:

```
|> first() |> count() |> group() |> count()
```

This will enable a pushdown so only one row is read instead of the entire thing.

**Comment by nathanielc** [comment] 2020-08-18 17:01
Related https://github.com/influxdata/flux/issues/3122

**Comment by rickspencer3** [comment] 2020-11-30 19:25
since https://github.com/influxdata/flux/issues/3122 is done, I believe this issue is a dupe of that and also done

**Closed by rickspencer3** 2020-11-30 19:25 UTC
Labels: Lighthouse, community, team/query
